import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]

dimensions = { columns = 160, lines = 50 }
opacity = 0.95

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }

size = 15.0

[keyboard]
bindings = [{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" }]
