import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
opacity = 0.95

[window.dimensions]
columns = 140  
lines = 40    

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }

size = 14.0

[keyboard]
bindings = [{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" }]
