import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }

size = 10.0

[keyboard]
bindings = [{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" }]
