[battery]
disabled = true

[cmd_duration]

[directory]
truncation_symbol = "--/"
truncate_to_repo = true
read_only = "  "

[directory.substitutions]
"Documents" = " 󰈙 "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "

[git_branch]

[git_commit]
disabled = false
commit_hash_length = 4
tag_disabled = false

[git_state]
disabled = true

[hostname]

[jobs]

[kubernetes]
symbol = "⎈ "
disabled = true

[docker_context]
symbol = " "
style = "bg:fifth fg:white"
format = '[$symbol $context ]($style)'
[line_break]
disabled = false

[c]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:white"
format = '[$symbol($version) ]($style)'

[golang]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:white"
format = '[$symbol($version) ]($style)'

[python]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:white"
python_binary = [
  "./venv/bin/python",
  "./env/Scripts/python",
  "python",
  "python3",
  "python2",
]
format = '[$symbol($version)]($style)[ (\($virtualenv\)) ](bg:fourth fg:white)'

[haskell]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:white"
format = '[$symbol($version) ]($style)'

[nodejs]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:white"
format = '[$symbol($version) ]($style)'

[rust]
symbol = " "
version_format = "${raw}"
style = "bg:fourth fg:white"
format = '[$symbol($version) ]($style)'

[time]
disabled = true

[username]
disabled = false
